package Task1;

import javax.swing.JOptionPane;

/**
 * Offers a UI to perform calculations under modulus.
 * @author Matthew Carpenter 14012396
 */
public class ModOperationsApp extends javax.swing.JFrame {

    // <editor-fold defaultstate="collapsed" desc="Constructor">
    
    /**
     * Creates new form ModOperationsApp
     */
    public ModOperationsApp() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddition = new javax.swing.JLabel();
        txtbAdditionPrimary = new javax.swing.JTextField();
        lblAdditionMod = new javax.swing.JLabel();
        txtbAdditionTertiary = new javax.swing.JTextField();
        btnAdditionCalculate = new javax.swing.JButton();
        txtbAdditionSecondary = new javax.swing.JTextField();
        lblAdditionSymbol = new javax.swing.JLabel();
        lblAdditionResult = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMultiplication = new javax.swing.JLabel();
        txtbMultiplicationPrimary = new javax.swing.JTextField();
        lblMultiplicationMod = new javax.swing.JLabel();
        txtbMultiplicationTertiary = new javax.swing.JTextField();
        btnMultiplicationCalculate = new javax.swing.JButton();
        txtbMultiplicationSecondary = new javax.swing.JTextField();
        lblMultiplicationSymbol = new javax.swing.JLabel();
        lblMultiplicationResult = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblDivision = new javax.swing.JLabel();
        txtbDivisionPrimary = new javax.swing.JTextField();
        lblDivisionMod = new javax.swing.JLabel();
        txtbDivisionTertiary = new javax.swing.JTextField();
        btnDivisionCalculate = new javax.swing.JButton();
        txtbDivisionSecondary = new javax.swing.JTextField();
        lblDivisionSymbol = new javax.swing.JLabel();
        lblDivisionResult = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtbInversePrimary = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblDivisionMod1 = new javax.swing.JLabel();
        txtbInverseSecondary = new javax.swing.JTextField();
        btnInverseCalculate = new javax.swing.JButton();
        lblInverseResult = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblSquareRoot = new javax.swing.JLabel();
        txtbSquareRootPrimary = new javax.swing.JTextField();
        lblDivisionMod2 = new javax.swing.JLabel();
        txtbSquareRootSecondary = new javax.swing.JTextField();
        btnSquareRootCalculate = new javax.swing.JButton();
        lblSquareRootResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAddition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAddition.setText("Addition:");

        lblAdditionMod.setText("mod");

        btnAdditionCalculate.setText("Calculate");
        btnAdditionCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdditionCalculateActionPerformed(evt);
            }
        });

        lblAdditionSymbol.setText("+");

        lblMultiplication.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMultiplication.setText("Multiplication:");

        lblMultiplicationMod.setText("mod");

        btnMultiplicationCalculate.setText("Calculate");
        btnMultiplicationCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicationCalculateActionPerformed(evt);
            }
        });

        lblMultiplicationSymbol.setText("*");

        lblDivision.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDivision.setText("Division:");

        lblDivisionMod.setText("mod");

        btnDivisionCalculate.setText("Calculate");
        btnDivisionCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionCalculateActionPerformed(evt);
            }
        });

        lblDivisionSymbol.setText("/");

        jLabel1.setText("Inverse:");

        jLabel2.setText(" -1");

        lblDivisionMod1.setText("mod");

        btnInverseCalculate.setText("Calculate");
        btnInverseCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInverseCalculateActionPerformed(evt);
            }
        });

        lblSquareRoot.setText("Square Root:");

        lblDivisionMod2.setText("mod");

        btnSquareRootCalculate.setText("Calculate");
        btnSquareRootCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAddition)
                            .addComponent(lblMultiplication)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1)
                                    .addComponent(jSeparator2)
                                    .addComponent(jSeparator3))
                                .addContainerGap())
                            .addComponent(lblDivision)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtbAdditionPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAdditionSymbol)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbAdditionSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAdditionMod)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbAdditionTertiary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdditionCalculate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAdditionResult, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtbMultiplicationPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMultiplicationSymbol)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbMultiplicationSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMultiplicationMod)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbMultiplicationTertiary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMultiplicationCalculate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMultiplicationResult, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtbDivisionPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDivisionSymbol)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbDivisionSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDivisionMod)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbDivisionTertiary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDivisionCalculate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDivisionResult, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtbInversePrimary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(57, 57, 57)
                                .addComponent(lblDivisionMod1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbInverseSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInverseCalculate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInverseResult))
                            .addComponent(lblSquareRoot))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtbSquareRootPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDivisionMod2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbSquareRootSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSquareRootCalculate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSquareRootResult, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbAdditionPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdditionMod)
                    .addComponent(txtbAdditionTertiary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdditionCalculate)
                    .addComponent(txtbAdditionSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdditionSymbol)
                    .addComponent(lblAdditionResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMultiplication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbMultiplicationPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMultiplicationMod)
                    .addComponent(txtbMultiplicationTertiary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicationCalculate)
                    .addComponent(txtbMultiplicationSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMultiplicationSymbol)
                    .addComponent(lblMultiplicationResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDivision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbDivisionPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDivisionMod)
                    .addComponent(txtbDivisionTertiary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivisionCalculate)
                    .addComponent(txtbDivisionSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDivisionSymbol)
                    .addComponent(lblDivisionResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDivisionMod1)
                                .addComponent(txtbInverseSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnInverseCalculate)
                                .addComponent(lblInverseResult))
                            .addComponent(txtbInversePrimary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSquareRoot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDivisionMod2)
                        .addComponent(txtbSquareRootSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSquareRootCalculate)
                        .addComponent(lblSquareRootResult))
                    .addComponent(txtbSquareRootPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Methods">
    
    // Event handler for btnAdditionCalculate. Carries out an addition operation under modulus.
    private void btnAdditionCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdditionCalculateActionPerformed
        // get input from user interface
        String primaryString = txtbAdditionPrimary.getText();
        String secondaryString = txtbAdditionSecondary.getText();
        String modulusString = txtbAdditionTertiary.getText();
        // check that all fields have been filled out
        if (primaryString.length() == 0 || secondaryString.length() == 0 || modulusString.length() == 0) {
            JOptionPane.showMessageDialog(this, "Not all fields filled out.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            // parse values
            int primary = Integer.parseInt(primaryString);
            int secondary = Integer.parseInt(secondaryString);
            int modulus = Integer.parseInt(modulusString);
            // carry out addition and display result
            int result = ModCalculator.Addition(primary, secondary, modulus);
            lblAdditionResult.setText(Integer.toString(result));
        }
        // invalid value entered, show error dialog
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid field.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdditionCalculateActionPerformed

    // Event handler for btnMultiplicationCalculate. Carries out a multiplication operation under modulus.
    private void btnMultiplicationCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicationCalculateActionPerformed
        // get input from user interface
        String primaryString = txtbMultiplicationPrimary.getText();
        String secondaryString = txtbMultiplicationSecondary.getText();
        String modulusString = txtbMultiplicationTertiary.getText();
        // check that all fields have been filled out
        if (primaryString.length() == 0 || secondaryString.length() == 0 || modulusString.length() == 0) {
            JOptionPane.showMessageDialog(this, "Not all fields filled out.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            // parse values
            int primary = Integer.parseInt(primaryString);
            int secondary = Integer.parseInt(secondaryString);
            int modulus = Integer.parseInt(modulusString);
            // carry out multiplication and display result
            int result = ModCalculator.Multiplication(primary, secondary, modulus);
            lblMultiplicationResult.setText(Integer.toString(result));
        }
        // invalid value entered, show error dialog
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid field.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMultiplicationCalculateActionPerformed

    // Event handler for btnDivisionCalculate. Carries out a division operation under modulus.
    private void btnDivisionCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionCalculateActionPerformed
        // get input from user interface
        String primaryString = txtbDivisionPrimary.getText();
        String secondaryString = txtbDivisionSecondary.getText();
        String modulusString = txtbDivisionTertiary.getText();
        // check that all fields have been filled out
        if (primaryString.length() == 0 || secondaryString.length() == 0 || modulusString.length() == 0) {
            JOptionPane.showMessageDialog(this, "Not all fields filled out.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            // parse values
            int primary = Integer.parseInt(primaryString);
            int secondary = Integer.parseInt(secondaryString);
            int modulus = Integer.parseInt(modulusString);
            // carry out division and display result
            int result = ModCalculator.Division(primary, secondary, modulus);
            lblDivisionResult.setText(Integer.toString(result));
        }
        // invalid value entered, show error dialog
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid field.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDivisionCalculateActionPerformed

    // Event handler for btnInverseCalculate. Carries out an inverse operation under modulus.
    private void btnInverseCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInverseCalculateActionPerformed
        // get input from user interface
        String primaryString = txtbInversePrimary.getText();
        String modulusString = txtbInverseSecondary.getText();
        // check that all fields have been filled out
        if (primaryString.length() == 0 || modulusString.length() == 0) {
            JOptionPane.showMessageDialog(this, "Not all fields filled out.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            // parse values
            int primary = Integer.parseInt(primaryString);
            int modulus = Integer.parseInt(modulusString);
            // carry out inverse calculation and display result
            int result = ModCalculator.GetModularInverse(primary, modulus);
            lblInverseResult.setText(Integer.toString(result));
        }
        // invalid value entered, show error dialog
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid field.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInverseCalculateActionPerformed

    // Event handler for btnSquareRootCalculate. Carries out a square root operation under modulus.
    private void btnSquareRootCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootCalculateActionPerformed
        // get input from user interface
        String primaryString = txtbSquareRootPrimary.getText();
        String modulusString = txtbSquareRootSecondary.getText();
        // check that all fields have been filled out
        if (primaryString.length() == 0 || modulusString.length() == 0) {
            JOptionPane.showMessageDialog(this, "Not all fields filled out.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            // parse values
            int primary = Integer.parseInt(primaryString);
            int modulus = Integer.parseInt(modulusString);
            // carry out square root calculation and display result
            int result = ModCalculator.GetSquareRoot(primary, modulus);
            // display result or no sq root
            if (result != -1) {
                lblSquareRootResult.setText(Integer.toString(result));
            }
            else {
                lblSquareRootResult.setText("no sq root");
            }
        }
        // invalid value entered, show error dialog
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid field.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSquareRootCalculateActionPerformed

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Main">
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModOperationsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModOperationsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModOperationsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModOperationsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModOperationsApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdditionCalculate;
    private javax.swing.JButton btnDivisionCalculate;
    private javax.swing.JButton btnInverseCalculate;
    private javax.swing.JButton btnMultiplicationCalculate;
    private javax.swing.JButton btnSquareRootCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAddition;
    private javax.swing.JLabel lblAdditionMod;
    private javax.swing.JLabel lblAdditionResult;
    private javax.swing.JLabel lblAdditionSymbol;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblDivisionMod;
    private javax.swing.JLabel lblDivisionMod1;
    private javax.swing.JLabel lblDivisionMod2;
    private javax.swing.JLabel lblDivisionResult;
    private javax.swing.JLabel lblDivisionSymbol;
    private javax.swing.JLabel lblInverseResult;
    private javax.swing.JLabel lblMultiplication;
    private javax.swing.JLabel lblMultiplicationMod;
    private javax.swing.JLabel lblMultiplicationResult;
    private javax.swing.JLabel lblMultiplicationSymbol;
    private javax.swing.JLabel lblSquareRoot;
    private javax.swing.JLabel lblSquareRootResult;
    private javax.swing.JTextField txtbAdditionPrimary;
    private javax.swing.JTextField txtbAdditionSecondary;
    private javax.swing.JTextField txtbAdditionTertiary;
    private javax.swing.JTextField txtbDivisionPrimary;
    private javax.swing.JTextField txtbDivisionSecondary;
    private javax.swing.JTextField txtbDivisionTertiary;
    private javax.swing.JTextField txtbInversePrimary;
    private javax.swing.JTextField txtbInverseSecondary;
    private javax.swing.JTextField txtbMultiplicationPrimary;
    private javax.swing.JTextField txtbMultiplicationSecondary;
    private javax.swing.JTextField txtbMultiplicationTertiary;
    private javax.swing.JTextField txtbSquareRootPrimary;
    private javax.swing.JTextField txtbSquareRootSecondary;
    // End of variables declaration//GEN-END:variables

    // </editor-fold>
    
}
