package Task2;

/**
 * Offers a UI for encoding and decoding BCH codes.
 * @author Matthew Carpenter 14012396
 */
public class BCHTenSixApp extends javax.swing.JFrame {

    // <editor-fold defaultstate="collapsed" desc="Constructor">
    
    /**
     * Creates new form TenDigitCode
     */
    public BCHTenSixApp() {
        initComponents();
        clearDecodeOutput();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncodeLabel = new javax.swing.JLabel();
        txtbEncodeEntry = new javax.swing.JTextField();
        lblEncodeResult = new javax.swing.JLabel();
        btnEncodeGenerate = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblDecodeLabel = new javax.swing.JLabel();
        txtbDecodeEntry = new javax.swing.JTextField();
        btnDecodeGenerate = new javax.swing.JButton();
        lblDecodeResult = new javax.swing.JLabel();
        lblDecodeErrorDetails = new javax.swing.JLabel();
        lblDecodeSyndValues = new javax.swing.JLabel();
        lblDecodePQRValues = new javax.swing.JLabel();
        lblDecodeIJABValues = new javax.swing.JLabel();
        btnDecodeClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEncodeLabel.setText("Enter 6 digits:");

        btnEncodeGenerate.setText("Encode");
        btnEncodeGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncodeGenerateActionPerformed(evt);
            }
        });

        lblDecodeLabel.setText("Enter 10 digits:");

        btnDecodeGenerate.setText("Decode");
        btnDecodeGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecodeGenerateActionPerformed(evt);
            }
        });

        lblDecodeResult.setText("Placeholder");

        lblDecodeErrorDetails.setText("Placeholder");

        lblDecodeSyndValues.setText("Placeholder");

        lblDecodePQRValues.setText("Placeholder");

        lblDecodeIJABValues.setText("Placeholder");

        btnDecodeClear.setText("Clear");
        btnDecodeClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecodeClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addComponent(lblEncodeResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEncodeLabel)
                                .addGap(14, 14, 14)
                                .addComponent(txtbEncodeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEncodeGenerate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDecodeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtbDecodeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDecodeGenerate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDecodeClear)))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addComponent(lblDecodeResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDecodeErrorDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDecodeSyndValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDecodePQRValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDecodeIJABValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncodeLabel)
                    .addComponent(txtbEncodeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncodeGenerate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEncodeResult, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDecodeLabel)
                    .addComponent(txtbDecodeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecodeGenerate)
                    .addComponent(btnDecodeClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDecodeResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDecodeErrorDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDecodeSyndValues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDecodePQRValues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDecodeIJABValues)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Methods">
    
    // <editor-fold defaultstate="collapsed" desc="Event Handlers">
    
    // Event handler for btnEncodeGenerate. Generates an encoded number from the entered digits.
    private void btnEncodeGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncodeGenerateActionPerformed
        String digits = txtbEncodeEntry.getText().replace(" ", "");
        lblEncodeResult.setText(BCHTenSix.encode(digits));
    }//GEN-LAST:event_btnEncodeGenerateActionPerformed

    // Event handler for btnDecodeGenerate. Decodes the entered number to check for errors and displays the relevant result.
    private void btnDecodeGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecodeGenerateActionPerformed
        clearDecodeOutput();
        String digits = txtbDecodeEntry.getText().replace(" ", "");
        DecodeResult result = BCHTenSix.decode(digits);
        String resultString = "";
        String syndromeString = "";
        String pqrString = "";
        String ijabString = "";
        String errorDetailsString = "";
        int[] syndromes = result.getSyndromes();
        switch (result.getResult()) {
            case VALID:
                resultString = "No error.";
                syndromeString = "syndromes = (" + syndromes[0] + ", " + syndromes[1] + ", " + syndromes[2] + ", " + syndromes[3] + ")";
                break;
            case SINGLE_ERROR:
                resultString = "Corrected: " + result.getCorrected();
                syndromeString = "syndromes = (" + syndromes[0] + ", " + syndromes[1] + ", " + syndromes[2] + ", " + syndromes[3] + ")";
                pqrString = "P = " + result.getP() + ", Q = " + result.getQ() + ", R = " + result.getR();
                ijabString = "i = " + result.getI() + ", a = " + result.getA();
                errorDetailsString = result.getErrorDetails();
                break;
            case DOUBLE_ERROR:
                resultString = "Corrected: " + result.getCorrected();
                syndromeString = "syndromes = (" + syndromes[0] + ", " + syndromes[1] + ", " + syndromes[2] + ", " + syndromes[3] + ")";
                pqrString = "P = " + result.getP() + ", Q = " + result.getQ() + ", R = " + result.getR();
                ijabString = "i = " + result.getI() + ", a = " + result.getA() + ", j = " + result.getJ() + ", b = " + result.getB();
                errorDetailsString = result.getErrorDetails();
                break;
            case MORE_THAN_TWO_ERRORS:
                resultString = "Unable to correct.";
                syndromeString = "syndromes = (" + syndromes[0] + ", " + syndromes[1] + ", " + syndromes[2] + ", " + syndromes[3] + ")";
                pqrString = "P = " + result.getP() + ", Q = " + result.getQ() + ", R = " + result.getR();
                ijabString = "i = " + result.getI() + ", a = " + result.getA() + ", j = " + result.getJ() + ", b = " + result.getB();
                errorDetailsString = result.getErrorDetails();
                break;
            case INCORRECT_FORMAT:
                resultString = "Incorrect format.";
                break;
        }
        lblDecodeResult.setText(resultString);
        lblDecodeSyndValues.setText(syndromeString);
        lblDecodePQRValues.setText(pqrString);
        lblDecodeIJABValues.setText(ijabString);
        lblDecodeErrorDetails.setText(errorDetailsString);
    }//GEN-LAST:event_btnDecodeGenerateActionPerformed

    // Event handler for btnDecodeClear. Clears the input and output for the decoding.
    private void btnDecodeClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecodeClearActionPerformed
        clearDecodeOutput();
        txtbDecodeEntry.setText("");
    }//GEN-LAST:event_btnDecodeClearActionPerformed

    // </editor-fold>
    
    // Clears the decode outputs on the user interface
    private void clearDecodeOutput() {
        lblDecodeResult.setText("");
        lblDecodeErrorDetails.setText("");
        lblDecodeSyndValues.setText("");
        lblDecodePQRValues.setText("");
        lblDecodeIJABValues.setText("");
    }
    
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Main">
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BCHTenSixApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BCHTenSixApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BCHTenSixApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BCHTenSixApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BCHTenSixApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecodeClear;
    private javax.swing.JButton btnDecodeGenerate;
    private javax.swing.JButton btnEncodeGenerate;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDecodeErrorDetails;
    private javax.swing.JLabel lblDecodeIJABValues;
    private javax.swing.JLabel lblDecodeLabel;
    private javax.swing.JLabel lblDecodePQRValues;
    private javax.swing.JLabel lblDecodeResult;
    private javax.swing.JLabel lblDecodeSyndValues;
    private javax.swing.JLabel lblEncodeLabel;
    private javax.swing.JLabel lblEncodeResult;
    private javax.swing.JTextField txtbDecodeEntry;
    private javax.swing.JTextField txtbEncodeEntry;
    // End of variables declaration//GEN-END:variables

    // </editor-fold>

}
